### Get all sound mixes
GET http://136.115.91.235:4005/soundmixer/ HTTP/1.1
Content-Type: application/json

###

### Get sound mix by ID
GET http://136.115.91.235:4005/soundmixer/1 HTTP/1.1
Content-Type: application/json

###

