-- This script was aligned to the ERD design (integer IDs)
-- Legacy: Removed addition of DeletedAt columns (we ignore DeletedAt)
-- Optional: remove old partial indexes related to DeletedAt (safe no-op if absent)
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  CREATE TYPE task_priority AS ENUM ('Low','Medium','High','Urgent');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  CREATE TYPE invoice_type AS ENUM ('Student','Teacher');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  CREATE TYPE invoice_status AS ENUM ('Draft','Issued','Paid','Overdue','Canceled');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  CREATE TYPE notification_type AS ENUM ('Message','Alert','Reminder');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  CREATE TYPE notification_priority AS ENUM ('Low','Normal','High','Critical');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  CREATE TYPE gender_type AS ENUM ('Male','Female','Other');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  CREATE TYPE service_type AS ENUM ('Monthly','Daily','Hourly','Other');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  CREATE TYPE student_payment_method AS ENUM ('Cash','Card','Transfer');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  CREATE TYPE student_payment_status AS ENUM ('Pending','Partial','Paid','Canceled');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  CREATE TYPE teacher_payment_method AS ENUM ('Transfer','Cash','Check');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  CREATE TYPE teacher_payment_status AS ENUM ('Pending','Paid','Canceled');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- Tables per ERD
CREATE TABLE IF NOT EXISTS public.activity (
  "ActivityID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Name" varchar(200) NOT NULL,
  "Description" text,
  "GradeID" integer,
  "EmpID" integer,
  "ScheduledDate" date,
  "StartTime" time without time zone,
  "EndTime" time without time zone,
  "Location" varchar(200),
  "Category" varchar(50),
  "Status" activity_status DEFAULT 'Planned',
  "IsActive" smallint NOT NULL DEFAULT 1,
  "ImagePath" varchar(512),
  "CreatedBy" integer,
  "CreatedAt" timestamp without time zone NOT NULL DEFAULT now(),
  "UpdatedAt" timestamp without time zone
);

CREATE TABLE IF NOT EXISTS public.activity_media (
  "MediaID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ActivityID" integer NOT NULL,
  "MediaType" media_type NOT NULL DEFAULT 'Image',
  "FilePath" varchar(512) NOT NULL,
  "FileSize" integer,
  "Caption" varchar(255),
  "UploadedBy" integer,
  "CreatedAt" timestamp without time zone NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.attendance (
  "AttendanceID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "StudentID" integer NOT NULL,
  "Date" date NOT NULL,
  "CheckInTime" time without time zone,
  "CheckOutTime" time without time zone,
  "Status" attendance_status NOT NULL DEFAULT 'Present',
  "IsLate" smallint DEFAULT 0,
  "LateMinutes" integer DEFAULT 0,
  "Notes" text,
  "CheckedInBy" integer,
  "CheckedOutBy" integer,
  "CreatedAt" timestamp without time zone NOT NULL DEFAULT now(),
  "UpdatedAt" timestamp without time zone
);

CREATE TABLE IF NOT EXISTS public.audit_log (
  "LogID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "UserID" integer,
  "Action" varchar(100) NOT NULL,
  "TableName" varchar(50),
  "RecordID" integer,
  "OldData" jsonb,
  "NewData" jsonb,
  "IPAddress" varchar(45),
  "UserAgent" varchar(255),
  "CreatedAt" timestamp without time zone NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.employee (
  "EmpID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "FirstName" varchar(50) NOT NULL,
  "LastName" varchar(50) NOT NULL,
  "DocumentNumber" varchar(10),
  "Position" varchar(100) NOT NULL,
  "Email" varchar(100),
  "PhoneNumber" varchar(10),
  "Address" varchar(255),
  "HireDate" date,
  "TerminationDate" date,
  "Salary" numeric(10,2),
  "BankAccount" varchar(50),
  "EmergencyContact" varchar(100),
  "EmergencyPhone" varchar(20),
  "Qualifications" text,
  "ProfilePicture" varchar(512),
  "IsActive" smallint NOT NULL DEFAULT 1,
  "UserID" integer,
  "CreatedAt" timestamp without time zone NOT NULL DEFAULT now(),
  "UpdatedAt" timestamp without time zone
);

-- Unicidad y validación básica de cédula ecuatoriana para empleados
DO $$ BEGIN
  ALTER TABLE public.employee
    ADD CONSTRAINT unique_employee_document UNIQUE ("DocumentNumber");
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE public.employee
    ADD CONSTRAINT chk_employee_document_cedula CHECK (
      "DocumentNumber" IS NULL OR "DocumentNumber" ~ '^[0-9]{10}$'
    );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS public.employee_task (
  "TaskID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "EmpID" integer NOT NULL,
  "TaskName" varchar(200) NOT NULL,
  "Description" text,
  "DueDate" date,
  "Status" task_status DEFAULT 'Pending',
  "Priority" task_priority DEFAULT 'Medium',
  "CompletedDate" date,
  "CreatedBy" integer,
  "CreatedAt" timestamp without time zone NOT NULL DEFAULT now(),
  "UpdatedAt" timestamp without time zone
);

CREATE TABLE IF NOT EXISTS public.grade (
  "GradeID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "GradeName" varchar(100) NOT NULL,
  "Description" text,
  "AgeRangeMin" integer,
  "AgeRangeMax" integer,
  "MaxCapacity" integer,
  "IsActive" smallint NOT NULL DEFAULT 1,
  "CreatedAt" timestamp without time zone NOT NULL DEFAULT now(),
  "UpdatedAt" timestamp without time zone
);

CREATE TABLE IF NOT EXISTS public.guardian (
  "GuardianID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "FirstName" varchar(50) NOT NULL,
  "LastName" varchar(50) NOT NULL,
  "DocumentNumber" varchar(10),
  "Relationship" varchar(50) NOT NULL,
  "PhoneNumber" varchar(10),
  "Email" varchar(100),
  "Address" varchar(255),
  "Occupation" varchar(100),
  "WorkPhone" varchar(20),
  "UserID" integer,
  "IsActive" smallint NOT NULL DEFAULT 1,
  "IsEmergencyContact" smallint DEFAULT 0,
  "IsAuthorizedPickup" smallint DEFAULT 1,
  "CreatedAt" timestamp without time zone NOT NULL DEFAULT now(),
  "UpdatedAt" timestamp without time zone
);

CREATE TABLE IF NOT EXISTS public.invoice (
  "InvoiceID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "InvoiceNumber" varchar(50) NOT NULL,
  "InvoiceType" invoice_type NOT NULL DEFAULT 'Student',
  "ReferenceID" integer NOT NULL,
  "IssueDate" date NOT NULL,
  "DueDate" date,
  "TotalAmount" numeric(10,2) NOT NULL,
  "TaxAmount" numeric(10,2) DEFAULT 0,
  "DiscountAmount" numeric(10,2) DEFAULT 0,
  "FinalAmount" numeric(10,2) NOT NULL,
  "Description" text,
  "Status" invoice_status DEFAULT 'Draft',
  "FilePath" varchar(512),
  "CreatedBy" integer,
  "CreatedAt" timestamp without time zone NOT NULL DEFAULT now(),
  "UpdatedAt" timestamp without time zone,
  CONSTRAINT "invoice_InvoiceNumber_key" UNIQUE ("InvoiceNumber")
);

CREATE TABLE IF NOT EXISTS public.notification (
  "NotificationID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "SenderID" integer,
  "ReceiverID" integer NOT NULL,
  "Type" notification_type NOT NULL DEFAULT 'Message',
  "Priority" notification_priority DEFAULT 'Normal',
  "Subject" varchar(200),
  "Message" text NOT NULL,
  "IsRead" smallint DEFAULT 0,
  "ReadAt" timestamp without time zone,
  "RelatedModule" varchar(50),
  "RelatedID" integer,
  "ExpiresAt" timestamp without time zone,
  "CreatedAt" timestamp without time zone NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.permission (
  "PermissionID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "PermissionName" varchar(100) NOT NULL,
  "Module" varchar(50) NOT NULL,
  "Action" varchar(50) NOT NULL,
  "Description" text,
  "CreatedAt" timestamp without time zone NOT NULL DEFAULT now(),
  "Link" varchar(200),
  "Icon" varchar(50),
  CONSTRAINT unique_permission UNIQUE ("Module", "Action")
);

CREATE TABLE IF NOT EXISTS public.role (
  "RoleID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "RoleName" varchar(50) NOT NULL,
  "Description" text,
  "IsActive" smallint NOT NULL DEFAULT 1,
  "CreatedAt" timestamp without time zone NOT NULL DEFAULT now(),
  "UpdatedAt" timestamp without time zone,
  CONSTRAINT "role_RoleName_key" UNIQUE ("RoleName")
);

-- Compatibility view for frontend expecting table `roles` with columns id/name/description
CREATE OR REPLACE VIEW public.roles AS
SELECT "RoleID" AS id,
       "RoleName" AS name,
       "Description" AS description,
       "IsActive" AS is_active,
       "CreatedAt" AS created_at,
       "UpdatedAt" AS updated_at
FROM public.role;

CREATE TABLE IF NOT EXISTS public.role_permission (
  "RolePermissionID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "RoleID" integer NOT NULL,
  "PermissionID" integer NOT NULL,
  "GrantedAt" timestamp without time zone NOT NULL DEFAULT now(),
  CONSTRAINT unique_role_permission UNIQUE ("RoleID", "PermissionID")
);

CREATE TABLE IF NOT EXISTS public.session (
  "SessionID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "UserID" integer NOT NULL,
  "Token" varchar(255) NOT NULL,
  "IPAddress" varchar(45),
  "UserAgent" varchar(255),
  "ExpiresAt" timestamp without time zone NOT NULL,
  "CreatedAt" timestamp without time zone NOT NULL DEFAULT now(),
  CONSTRAINT "session_Token_key" UNIQUE ("Token")
);

CREATE TABLE IF NOT EXISTS public."user" (
  "UserID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "UserName" varchar(50) NOT NULL,
  "PasswordHash" varchar(255),
  "Email" varchar(100) NOT NULL,
  "FirstName" varchar(50),
  "LastName" varchar(50),
  "Phone" varchar(20),
  "Address" varchar(255),
  "IsActive" smallint NOT NULL DEFAULT 1,
  "LastLogin" timestamp without time zone,
  "PasswordResetToken" varchar(255),
  "PasswordResetExpires" timestamp without time zone,
  "CreatedAt" timestamp without time zone NOT NULL DEFAULT now(),
  "UpdatedAt" timestamp without time zone,
  "AuthUserID" uuid,
  CONSTRAINT "user_AuthUserID_key" UNIQUE ("AuthUserID"),
  CONSTRAINT "user_Email_key" UNIQUE ("Email"),
  CONSTRAINT "user_UserName_key" UNIQUE ("UserName")
);

CREATE TABLE IF NOT EXISTS public.user_role (
  "UserRoleID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "UserID" integer NOT NULL,
  "RoleID" integer NOT NULL,
  "AssignedAt" timestamp without time zone NOT NULL DEFAULT now(),
  "AssignedBy" integer,
  CONSTRAINT unique_user_role UNIQUE ("UserID", "RoleID")
);

CREATE TABLE IF NOT EXISTS public.student (
  "StudentID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "FirstName" varchar(50) NOT NULL,
  "LastName" varchar(50) NOT NULL,
  "BirthDate" date NOT NULL,
  "Gender" gender_type,
  "DocumentNumber" varchar(20),
  "Address" varchar(255),
  "Email" varchar(100),
  "PhoneNumber" varchar(20),
  "GradeID" integer,
  "ProfilePicture" varchar(512),
  "MedicalInfo" text,
  "EmergencyContact" varchar(100),
  "EmergencyPhone" varchar(20),
  "IsActive" smallint NOT NULL DEFAULT 1,
  "IsRecurrent" smallint NOT NULL DEFAULT 1,
  "EnrollmentDate" date,
  "WithdrawalDate" date,
  "CreatedAt" timestamp without time zone NOT NULL DEFAULT now(),
  "UpdatedAt" timestamp without time zone
);

-- Unicidad y validación básica de cédula ecuatoriana para estudiantes
DO $$ BEGIN
  ALTER TABLE public.student
    ADD CONSTRAINT unique_student_document UNIQUE ("DocumentNumber");
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE public.student
    ADD CONSTRAINT chk_student_document_cedula CHECK (
      "DocumentNumber" IS NULL OR "DocumentNumber" ~ '^[0-9]{10}$'
    );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS public.student_guardian (
  "StudentGuardianID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "StudentID" integer NOT NULL,
  "GuardianID" integer NOT NULL,
  "Relationship" varchar(50),
  "IsPrimary" smallint DEFAULT 0,
  "Priority" integer DEFAULT 1,
  "CreatedAt" timestamp without time zone NOT NULL DEFAULT now(),
  CONSTRAINT unique_student_guardian UNIQUE ("StudentID", "GuardianID")
);

-- Ensure column exists for existing deployments
DO $$ BEGIN
  ALTER TABLE public.student_guardian ADD COLUMN IF NOT EXISTS "Relationship" varchar(50);
EXCEPTION WHEN others THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS public.student_observation (
  "ObservationID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "StudentID" integer NOT NULL,
  "EmpID" integer NOT NULL,
  "ObservationDate" date NOT NULL,
  "Category" varchar(50),
  "Observation" text NOT NULL,
  "IsPositive" smallint,
  "RequiresAction" smallint DEFAULT 0,
  "ActionTaken" text,
  "IsPrivate" smallint DEFAULT 0,
  "CreatedAt" timestamp without time zone NOT NULL DEFAULT now(),
  "UpdatedAt" timestamp without time zone
);

CREATE TABLE IF NOT EXISTS public.student_payment (
  "StudentPaymentID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "StudentID" integer NOT NULL,
  "ServiceType" service_type NOT NULL DEFAULT 'Monthly',
  "Hours" numeric(5,2),
  "RatePerHour" numeric(10,2),
  "MonthlyFee" numeric(10,2),
  "DailyFee" numeric(10,2),
  "TotalAmount" numeric(10,2) NOT NULL,
  "PaidAmount" numeric(10,2) DEFAULT 0,
  "BalanceRemaining" numeric(10,2) DEFAULT 0,
  "PaymentDate" date,
  "DueDate" date NOT NULL,
  "PaymentMethod" student_payment_method,
  "Status" student_payment_status NOT NULL DEFAULT 'Pending',
  "IsRecurrent" smallint DEFAULT 1,
  "StartDate" date,
  "EndDate" date,
  "InvoiceNumber" varchar(50),
  "TransactionReference" varchar(100),
  "Notes" text,
  "ProcessedBy" integer,
  "CreatedBy" integer,
  "CreatedAt" timestamp without time zone NOT NULL DEFAULT now(),
  "UpdatedAt" timestamp without time zone
);

CREATE TABLE IF NOT EXISTS public.teacher_payment (
  "TeacherPaymentID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "EmpID" integer NOT NULL,
  "PaymentPeriod" varchar(20) NOT NULL,
  "PeriodStartDate" date NOT NULL,
  "PeriodEndDate" date NOT NULL,
  "BaseSalary" numeric(10,2) NOT NULL,
  "Bonuses" numeric(10,2) DEFAULT 0,
  "Overtime" numeric(10,2) DEFAULT 0,
  "Deductions" numeric(10,2) DEFAULT 0,
  "TotalAmount" numeric(10,2) NOT NULL,
  "PaymentDate" date NOT NULL,
  "PaymentMethod" teacher_payment_method NOT NULL DEFAULT 'Transfer',
  "Status" teacher_payment_status NOT NULL DEFAULT 'Pending',
  "TransactionReference" varchar(100),
  "Notes" text,
  "ProcessedBy" integer,
  "CreatedBy" integer,
  "CreatedAt" timestamp without time zone NOT NULL DEFAULT now(),
  "UpdatedAt" timestamp without time zone
);

-- Foreign Keys per ERD
ALTER TABLE IF EXISTS public.activity
  ADD CONSTRAINT fk_activity_created_by FOREIGN KEY ("CreatedBy") REFERENCES public."user"("UserID") ON DELETE SET NULL;
ALTER TABLE IF EXISTS public.activity
  ADD CONSTRAINT fk_activity_employee FOREIGN KEY ("EmpID") REFERENCES public.employee("EmpID") ON DELETE SET NULL;
ALTER TABLE IF EXISTS public.activity
  ADD CONSTRAINT fk_activity_grade FOREIGN KEY ("GradeID") REFERENCES public.grade("GradeID") ON DELETE SET NULL;

ALTER TABLE IF EXISTS public.activity_media
  ADD CONSTRAINT fk_activity_media_activity FOREIGN KEY ("ActivityID") REFERENCES public.activity("ActivityID") ON DELETE CASCADE;
ALTER TABLE IF EXISTS public.activity_media
  ADD CONSTRAINT fk_activity_media_uploaded_by FOREIGN KEY ("UploadedBy") REFERENCES public."user"("UserID") ON DELETE SET NULL;

ALTER TABLE IF EXISTS public.attendance
  ADD CONSTRAINT fk_attendance_checked_in_by FOREIGN KEY ("CheckedInBy") REFERENCES public.employee("EmpID") ON DELETE SET NULL;
ALTER TABLE IF EXISTS public.attendance
  ADD CONSTRAINT fk_attendance_checked_out_by FOREIGN KEY ("CheckedOutBy") REFERENCES public.employee("EmpID") ON DELETE SET NULL;
ALTER TABLE IF EXISTS public.attendance
  ADD CONSTRAINT fk_attendance_student FOREIGN KEY ("StudentID") REFERENCES public.student("StudentID") ON DELETE CASCADE;

ALTER TABLE IF EXISTS public.audit_log
  ADD CONSTRAINT fk_audit_log_user FOREIGN KEY ("UserID") REFERENCES public."user"("UserID") ON DELETE SET NULL;

ALTER TABLE IF EXISTS public.employee
  ADD CONSTRAINT fk_employee_user FOREIGN KEY ("UserID") REFERENCES public."user"("UserID") ON DELETE SET NULL;

ALTER TABLE IF EXISTS public.employee_task
  ADD CONSTRAINT fk_employee_task_created_by FOREIGN KEY ("CreatedBy") REFERENCES public."user"("UserID") ON DELETE SET NULL;
ALTER TABLE IF EXISTS public.employee_task
  ADD CONSTRAINT fk_employee_task_employee FOREIGN KEY ("EmpID") REFERENCES public.employee("EmpID") ON DELETE CASCADE;

ALTER TABLE IF EXISTS public.invoice
  ADD CONSTRAINT fk_invoice_created_by FOREIGN KEY ("CreatedBy") REFERENCES public."user"("UserID") ON DELETE SET NULL;

ALTER TABLE IF EXISTS public.notification
  ADD CONSTRAINT fk_notification_receiver FOREIGN KEY ("ReceiverID") REFERENCES public."user"("UserID") ON DELETE CASCADE;
ALTER TABLE IF EXISTS public.notification
  ADD CONSTRAINT fk_notification_sender FOREIGN KEY ("SenderID") REFERENCES public."user"("UserID") ON DELETE SET NULL;
ALTER TABLE IF EXISTS public.guardian
  ADD CONSTRAINT fk_guardian_user FOREIGN KEY ("UserID") REFERENCES public."user"("UserID") ON DELETE SET NULL;

ALTER TABLE IF EXISTS public.role_permission
  ADD CONSTRAINT fk_role_permission_permission FOREIGN KEY ("PermissionID") REFERENCES public.permission("PermissionID") ON DELETE CASCADE;
ALTER TABLE IF EXISTS public.role_permission
  ADD CONSTRAINT fk_role_permission_role FOREIGN KEY ("RoleID") REFERENCES public.role("RoleID") ON DELETE CASCADE;

ALTER TABLE IF EXISTS public.session
  ADD CONSTRAINT fk_session_user FOREIGN KEY ("UserID") REFERENCES public."user"("UserID") ON DELETE CASCADE;

ALTER TABLE IF EXISTS public.student
  ADD CONSTRAINT fk_student_grade FOREIGN KEY ("GradeID") REFERENCES public.grade("GradeID") ON DELETE SET NULL;

ALTER TABLE IF EXISTS public.student_guardian
  ADD CONSTRAINT fk_student_guardian_guardian FOREIGN KEY ("GuardianID") REFERENCES public.guardian("GuardianID") ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_student_guardian_guardian ON public.student_guardian("GuardianID");
ALTER TABLE IF EXISTS public.student_guardian
  ADD CONSTRAINT fk_student_guardian_student FOREIGN KEY ("StudentID") REFERENCES public.student("StudentID") ON DELETE CASCADE;

ALTER TABLE IF EXISTS public.student_observation
  ADD CONSTRAINT fk_observation_employee FOREIGN KEY ("EmpID") REFERENCES public.employee("EmpID") ON DELETE CASCADE;
ALTER TABLE IF EXISTS public.student_observation
  ADD CONSTRAINT fk_observation_student FOREIGN KEY ("StudentID") REFERENCES public.student("StudentID") ON DELETE CASCADE;

ALTER TABLE IF EXISTS public.student_payment
  ADD CONSTRAINT fk_student_payment_created_by FOREIGN KEY ("CreatedBy") REFERENCES public."user"("UserID") ON DELETE SET NULL;
ALTER TABLE IF EXISTS public.student_payment
  ADD CONSTRAINT fk_student_payment_processed_by FOREIGN KEY ("ProcessedBy") REFERENCES public.employee("EmpID") ON DELETE SET NULL;
ALTER TABLE IF EXISTS public.student_payment
  ADD CONSTRAINT fk_student_payment_student FOREIGN KEY ("StudentID") REFERENCES public.student("StudentID") ON DELETE CASCADE;

ALTER TABLE IF EXISTS public.teacher_payment
  ADD CONSTRAINT fk_teacher_payment_created_by FOREIGN KEY ("CreatedBy") REFERENCES public."user"("UserID") ON DELETE SET NULL;
ALTER TABLE IF EXISTS public.teacher_payment
  ADD CONSTRAINT fk_teacher_payment_employee FOREIGN KEY ("EmpID") REFERENCES public.employee("EmpID") ON DELETE CASCADE;
ALTER TABLE IF EXISTS public.teacher_payment
  ADD CONSTRAINT fk_teacher_payment_processed_by FOREIGN KEY ("ProcessedBy") REFERENCES public."user"("UserID") ON DELETE SET NULL;

ALTER TABLE IF EXISTS public.user_role
  ADD CONSTRAINT fk_user_role_assigned_by FOREIGN KEY ("AssignedBy") REFERENCES public."user"("UserID") ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_user_role_assigned_by ON public.user_role("AssignedBy");
ALTER TABLE IF EXISTS public.user_role
  ADD CONSTRAINT fk_user_role_role FOREIGN KEY ("RoleID") REFERENCES public.role("RoleID") ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_user_role_role ON public.user_role("RoleID");
ALTER TABLE IF EXISTS public.user_role
  ADD CONSTRAINT fk_user_role_user FOREIGN KEY ("UserID") REFERENCES public."user"("UserID") ON DELETE CASCADE;

-- Helpful view for permissions per user (by internal UserID)
CREATE OR REPLACE VIEW public.v_user_permissions AS
SELECT ur."UserID" AS user_id,
       r."RoleName" AS role_name,
       p."Module" AS module,
       p."Action" AS action,
       p."Link" AS link,
       p."Icon" AS icon,
       p."Description" AS description
FROM public.user_role ur
JOIN public.role r ON r."RoleID" = ur."RoleID"
JOIN public.role_permission rp ON rp."RoleID" = r."RoleID"
JOIN public.permission p ON p."PermissionID" = rp."PermissionID";

-- Seed basic permissions (idempotent)
INSERT INTO public.permission ("PermissionName","Module","Action","Description","Link","Icon") VALUES
  ('Dashboard View','Dashboard','view','Panel de Control','/html/welcome.html','fa-tachometer-alt'),
  ('Users & Roles View','Usuarios y Roles','view','Gestión de usuarios y roles','/html/users/users-roles.html','fa-users-cog'),
  ('Users & Roles Edit','Usuarios y Roles','edit','Administrar roles y permisos',NULL,'fa-users-cog'),
  ('Students View','Estudiantes','view','Gestión de estudiantes','/html/students.html','fa-user-graduate'),
  ('Students Edit','Estudiantes','edit','Editar estudiantes',NULL,'fa-user-graduate'),
  ('Grades View','Grados','view','Gestión de grados','/html/grades.html','fa-layer-group'),
  ('Grades Edit','Grados','edit','Editar grados',NULL,'fa-layer-group'),
  ('Guardians View','Responsables','view','Gestión de responsables','/html/guardians.html','fa-user-shield'),
  ('Guardians Edit','Responsables','edit','Editar responsables',NULL,'fa-user-shield'),
  ('Staff View','Personal','view','Gestión del personal','/html/staff.html','fa-user-tie'),
  ('Staff Edit','Personal','edit','Editar personal',NULL,'fa-user-tie'),
  ('Tasks View','Tareas','view','Asignación de tareas','/html/tasks.html','fa-list-check'),
  ('Tasks Edit','Tareas','edit','Editar tareas',NULL,'fa-list-check'),
  ('Attendance View','Asistencia','view','Registro de asistencia','/html/attendance.html','fa-clipboard-user'),
  ('Attendance Edit','Asistencia','edit','Editar asistencia',NULL,'fa-clipboard-user')
ON CONFLICT ("Module","Action") DO NOTHING;

-- Payments & Invoices permissions
INSERT INTO public.permission ("PermissionName","Module","Action","Description","Link","Icon") VALUES
  ('Payments View','Pagos','view','Gestión de pagos','/html/payments.html','fa-money-bill'),
  ('Payments Edit','Pagos','edit','Editar pagos',NULL,'fa-money-bill'),
  ('Invoices View','Facturación','view','Gestión de facturas','/html/invoices.html','fa-file-invoice'),
  ('Invoices Edit','Facturación','edit','Editar facturas',NULL,'fa-file-invoice')
ON CONFLICT ("Module","Action") DO NOTHING;

-- Activities permissions
INSERT INTO public.permission ("PermissionName","Module","Action","Description","Link","Icon") VALUES
  ('Activities View','Actividades','view','Gestión de actividades y multimedia','/html/activities.html','fa-calendar-days'),
  ('Activities Edit','Actividades','edit','Editar actividades y multimedia',NULL,'fa-calendar-days')
ON CONFLICT ("Module","Action") DO NOTHING;

-- Seed default Admin role and grant all permissions (idempotent)
INSERT INTO public.role ("RoleName","Description","IsActive")
VALUES ('Admin','Rol administrador con todos los permisos',1)
ON CONFLICT ("RoleName") DO NOTHING;

-- Additional roles for auto-provisioned users
INSERT INTO public.role ("RoleName","Description","IsActive")
VALUES ('Staff','Rol para empleados',1)
ON CONFLICT ("RoleName") DO NOTHING;
INSERT INTO public.role ("RoleName","Description","IsActive")
VALUES ('Guardian','Rol para responsables/padres',1)
ON CONFLICT ("RoleName") DO NOTHING;

-- Grant minimal permissions to Staff/Guardian (Activities view)
INSERT INTO public.role_permission ("RoleID","PermissionID")
SELECT r."RoleID", p."PermissionID"
FROM public.role r
JOIN public.permission p ON p."Module" = 'Actividades' AND p."Action" = 'view'
WHERE r."RoleName" IN ('Staff','Guardian')
ON CONFLICT ("RoleID","PermissionID") DO NOTHING;

INSERT INTO public.role_permission ("RoleID","PermissionID")
SELECT r."RoleID", p."PermissionID"
FROM public.role r
JOIN public.permission p ON true
WHERE r."RoleName" = 'Admin'
ON CONFLICT ("RoleID","PermissionID") DO NOTHING;

-- Helper: check if current auth user has a permission (module, action)
CREATE OR REPLACE FUNCTION public.has_permission(mod varchar, act varchar)
RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO public AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public."user" u
    JOIN public.user_role ur ON ur."UserID" = u."UserID"
    JOIN public.role_permission rp ON rp."RoleID" = ur."RoleID"
    JOIN public.permission p ON p."PermissionID" = rp."PermissionID"
    WHERE u."AuthUserID" = auth.uid()
      AND p."Module" = mod
      AND p."Action" = act
  );
$$;

-- Helper: generate unique username from first/last name (e.g., José Hernández -> johernandez, or johernandez2)
CREATE OR REPLACE FUNCTION public.gen_unique_username(first_name varchar, last_name varchar)
RETURNS varchar
LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path TO public AS $$
DECLARE
  base text;
  maxn int;
  candidate text;
BEGIN
  base := lower(regexp_replace(unaccent(coalesce(first_name,'')), '[^a-z0-9]+', '', 'g'));
  base := left(base, 2) || lower(regexp_replace(unaccent(coalesce(last_name,'')), '[^a-z0-9]+', '', 'g'));
  IF base = '' THEN
    base := 'user';
  END IF;
  SELECT max((regexp_matches(u."UserName", ('^' || base || '([0-9]+)$')))[1]::int) INTO maxn
  FROM public."user" u
  WHERE u."UserName" ~ ('^' || base || '[0-9]+$');

  IF EXISTS(SELECT 1 FROM public."user" WHERE "UserName" = base) THEN
    candidate := base || coalesce(maxn, 0) + 1;
  ELSE
    candidate := base;
  END IF;
  RETURN candidate;
END $$;

-- Helper: map username to email for username-based login
CREATE OR REPLACE FUNCTION public.get_email_by_username(p_username varchar)
RETURNS varchar
LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO public AS $$
  SELECT "Email"
  FROM public."user"
  WHERE lower("UserName") = lower(p_username)
  LIMIT 1;
$$;

-- Bootstrap helper: if current user has no role, assign Admin
CREATE OR REPLACE FUNCTION public.bootstrap_assign_admin()
RETURNS void
LANGUAGE plpgsql SECURITY DEFINER SET search_path TO public AS $$
DECLARE
  uid uuid;
  uid_int int;
  admin_role int;
  has_any boolean;
BEGIN
  uid := auth.uid();
  IF uid IS NULL THEN RETURN; END IF;
  SELECT "UserID" INTO uid_int FROM public."user" WHERE "AuthUserID" = uid;
  IF uid_int IS NULL THEN RETURN; END IF;
  SELECT EXISTS(SELECT 1 FROM public.user_role WHERE "UserID" = uid_int) INTO has_any;
  IF has_any THEN RETURN; END IF;
  SELECT "RoleID" INTO admin_role FROM public.role WHERE "RoleName" = 'Admin' LIMIT 1;
  IF admin_role IS NULL THEN RETURN; END IF;
  INSERT INTO public.user_role ("UserID","RoleID") VALUES (uid_int, admin_role)
  ON CONFLICT DO NOTHING;
END;
$$;

-- Optional: create partial indexes to speed active queries (ignore deleted)
-- Remove partial indexes based on DeletedAt (we ignore DeletedAt)
DO $$ BEGIN DROP INDEX IF EXISTS idx_activity_active; EXCEPTION WHEN others THEN NULL; END $$;
DO $$ BEGIN DROP INDEX IF EXISTS idx_student_active; EXCEPTION WHEN others THEN NULL; END $$;
DO $$ BEGIN DROP INDEX IF EXISTS idx_employee_active; EXCEPTION WHEN others THEN NULL; END $$;

-- Ensure IsActive columns exist and are normalized (idempotent)
DO $$ BEGIN
  ALTER TABLE public.employee ADD COLUMN IF NOT EXISTS "IsActive" smallint;
  UPDATE public.employee SET "IsActive" = 1 WHERE "IsActive" IS NULL;
  ALTER TABLE public.employee ALTER COLUMN "IsActive" SET DEFAULT 1;
  ALTER TABLE public.employee ALTER COLUMN "IsActive" SET NOT NULL;
EXCEPTION WHEN others THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE public.student ADD COLUMN IF NOT EXISTS "IsActive" smallint;
  UPDATE public.student SET "IsActive" = 1 WHERE "IsActive" IS NULL;
  ALTER TABLE public.student ALTER COLUMN "IsActive" SET DEFAULT 1;
  ALTER TABLE public.student ALTER COLUMN "IsActive" SET NOT NULL;
EXCEPTION WHEN others THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE public.grade ADD COLUMN IF NOT EXISTS "IsActive" smallint;
  UPDATE public.grade SET "IsActive" = 1 WHERE "IsActive" IS NULL;
  ALTER TABLE public.grade ALTER COLUMN "IsActive" SET DEFAULT 1;
  ALTER TABLE public.grade ALTER COLUMN "IsActive" SET NOT NULL;
EXCEPTION WHEN others THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE public.guardian ADD COLUMN IF NOT EXISTS "IsActive" smallint;
  UPDATE public.guardian SET "IsActive" = 1 WHERE "IsActive" IS NULL;
  ALTER TABLE public.guardian ALTER COLUMN "IsActive" SET DEFAULT 1;
  ALTER TABLE public.guardian ALTER COLUMN "IsActive" SET NOT NULL;
EXCEPTION WHEN others THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE public.activity ADD COLUMN IF NOT EXISTS "IsActive" smallint;
  UPDATE public.activity SET "IsActive" = 1 WHERE "IsActive" IS NULL;
  ALTER TABLE public.activity ALTER COLUMN "IsActive" SET DEFAULT 1;
  ALTER TABLE public.activity ALTER COLUMN "IsActive" SET NOT NULL;
EXCEPTION WHEN others THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE public.role ADD COLUMN IF NOT EXISTS "IsActive" smallint;
  UPDATE public.role SET "IsActive" = 1 WHERE "IsActive" IS NULL;
  ALTER TABLE public.role ALTER COLUMN "IsActive" SET DEFAULT 1;
  ALTER TABLE public.role ALTER COLUMN "IsActive" SET NOT NULL;
EXCEPTION WHEN others THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE public."user" ADD COLUMN IF NOT EXISTS "IsActive" smallint;
  UPDATE public."user" SET "IsActive" = 1 WHERE "IsActive" IS NULL;
  ALTER TABLE public."user" ALTER COLUMN "IsActive" SET DEFAULT 1;
  ALTER TABLE public."user" ALTER COLUMN "IsActive" SET NOT NULL;
EXCEPTION WHEN others THEN NULL; END $$;

-- Cleanup: drop legacy DeletedAt columns (safe if present)
DO $$ BEGIN ALTER TABLE public.activity DROP COLUMN IF EXISTS "DeletedAt"; EXCEPTION WHEN others THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.activity_media DROP COLUMN IF EXISTS "DeletedAt"; EXCEPTION WHEN others THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.grade DROP COLUMN IF EXISTS "DeletedAt"; EXCEPTION WHEN others THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.guardian DROP COLUMN IF EXISTS "DeletedAt"; EXCEPTION WHEN others THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.invoice DROP COLUMN IF EXISTS "DeletedAt"; EXCEPTION WHEN others THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.student DROP COLUMN IF EXISTS "DeletedAt"; EXCEPTION WHEN others THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.student_observation DROP COLUMN IF EXISTS "DeletedAt"; EXCEPTION WHEN others THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.student_payment DROP COLUMN IF EXISTS "DeletedAt"; EXCEPTION WHEN others THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.employee DROP COLUMN IF EXISTS "DeletedAt"; EXCEPTION WHEN others THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.employee_task DROP COLUMN IF EXISTS "DeletedAt"; EXCEPTION WHEN others THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.teacher_payment DROP COLUMN IF EXISTS "DeletedAt"; EXCEPTION WHEN others THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.notification DROP COLUMN IF EXISTS "DeletedAt"; EXCEPTION WHEN others THEN NULL; END $$;

-- Idempotent add IsActive to guardian/activity in existing deployments
DO $$ BEGIN ALTER TABLE public.guardian ADD COLUMN IF NOT EXISTS "IsActive" smallint NOT NULL DEFAULT 1; EXCEPTION WHEN others THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.activity ADD COLUMN IF NOT EXISTS "IsActive" smallint NOT NULL DEFAULT 1; EXCEPTION WHEN others THEN NULL; END $$;

-- Triggers: sincronizar IsActive del usuario cuando empleado/guardian cambia
CREATE OR REPLACE FUNCTION public.sync_user_active_from_employee()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NEW."UserID" IS NOT NULL THEN
    UPDATE public."user" u
      SET "IsActive" = CASE WHEN NEW."IsActive" = 0 THEN 0 ELSE 1 END,
          "UpdatedAt" = now()
      WHERE u."UserID" = NEW."UserID";
  END IF;
  RETURN NEW;
END$$;

DROP TRIGGER IF EXISTS trg_employee_sync_user_active ON public.employee;
CREATE TRIGGER trg_employee_sync_user_active
AFTER UPDATE OF "IsActive" ON public.employee
FOR EACH ROW EXECUTE FUNCTION public.sync_user_active_from_employee();

CREATE OR REPLACE FUNCTION public.sync_user_active_from_guardian()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NEW."UserID" IS NOT NULL THEN
    UPDATE public."user" u
      SET "IsActive" = CASE WHEN NEW."IsActive" = 0 THEN 0 ELSE 1 END,
          "UpdatedAt" = now()
      WHERE u."UserID" = NEW."UserID";
  END IF;
  RETURN NEW;
END$$;

DROP TRIGGER IF EXISTS trg_guardian_sync_user_active ON public.guardian;
CREATE TRIGGER trg_guardian_sync_user_active
AFTER UPDATE OF "IsActive" ON public.guardian
FOR EACH ROW EXECUTE FUNCTION public.sync_user_active_from_guardian();

-- Cascada: recalcular estado del guardian según estudiantes activos vinculados
CREATE OR REPLACE FUNCTION public.recalc_guardian_active_for_student(p_student_id integer)
RETURNS void LANGUAGE plpgsql AS $$
DECLARE
  g_id integer;
  cnt_active integer;
BEGIN
  FOR g_id IN SELECT "GuardianID" FROM public.student_guardian WHERE "StudentID" = p_student_id LOOP
    SELECT COUNT(*) INTO cnt_active
    FROM public.student_guardian sg
    JOIN public.student s ON s."StudentID" = sg."StudentID"
    WHERE sg."GuardianID" = g_id
      AND (s."IsActive" = 1);

    UPDATE public.guardian
      SET "IsActive" = CASE WHEN cnt_active > 0 THEN 1 ELSE 0 END,
          "UpdatedAt" = now()
      WHERE "GuardianID" = g_id;
  END LOOP;
END$$;

CREATE OR REPLACE FUNCTION public.trg_student_after_update()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  PERFORM public.recalc_guardian_active_for_student(NEW."StudentID");
  RETURN NEW;
END$$;

DROP TRIGGER IF EXISTS trg_student_after_update ON public.student;
CREATE TRIGGER trg_student_after_update
AFTER UPDATE OF "IsActive" ON public.student
FOR EACH ROW EXECUTE FUNCTION public.trg_student_after_update();

-- Recalcular también cuando se vincula o desvincula un responsable
CREATE OR REPLACE FUNCTION public.trg_student_guardian_change()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF (TG_OP = 'INSERT') THEN
    PERFORM public.recalc_guardian_active_for_student(NEW."StudentID");
  ELSIF (TG_OP = 'DELETE') THEN
    PERFORM public.recalc_guardian_active_for_student(OLD."StudentID");
  END IF;
  RETURN NULL;
END$$;

DROP TRIGGER IF EXISTS trg_student_guardian_change_ins ON public.student_guardian;
CREATE TRIGGER trg_student_guardian_change_ins
AFTER INSERT ON public.student_guardian
FOR EACH ROW EXECUTE FUNCTION public.trg_student_guardian_change();

DROP TRIGGER IF EXISTS trg_student_guardian_change_del ON public.student_guardian;
CREATE TRIGGER trg_student_guardian_change_del
AFTER DELETE ON public.student_guardian
FOR EACH ROW EXECUTE FUNCTION public.trg_student_guardian_change();
COMMIT;
