CREATE DATABASE IF NOT EXISTS chicken CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE chicken;

CREATE TABLE IF NOT EXISTS chickens (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  gallinero TINYINT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;
